//{name:"dummy",url:"",color:"#00ff00",child:[]},

var categoryList = [

{name:"部署／グループをみる",url:"",color:"#ffa458",child:[
  {name:"モバイル事業部",url:"",color:"#ffa458",child:[
    {name:"営業1グループ",url:"",color:"#ffa458",child:[
      {name:"スタッフ",url:"http://qrator.gsj.intranet/search/keyword?g[]=1&s_v=1",color:"#ffa458",child:[]},
      {name:"プロジェクト",url:"http://qrator.gsj.intranet/search/keyword?g[]=1&p_v=1",color:"#ffa458",child:[]},
      {name:"取引先",url:"http://qrator.gsj.intranet/search/keyword?g[]=1&c_v=1",color:"#ffa458",child:[]},
      {name:"グループ詳細",url:"http://qrator.gsj.intranet/group/detail/1",color:"#ffa458",child:[]}]},
    {name:"営業2グループ",url:"",color:"#ffa458",child:[
      {name:"スタッフ",url:"http://qrator.gsj.intranet/search/keyword?g[]=2&s_v=1",color:"#ffa458",child:[]},
      {name:"プロジェクト",url:"http://qrator.gsj.intranet/search/keyword?g[]=2&p_v=1",color:"#ffa458",child:[]},
      {name:"取引先",url:"http://qrator.gsj.intranet/search/keyword?g[]=2&c_v=1",color:"#ffa458",child:[]},
      {name:"グループ詳細",url:"http://qrator.gsj.intranet/group/detail/2",color:"#ffa458",child:[]}]},
    {name:"営業3グループ",url:"",color:"#ffa458",child:[
      {name:"スタッフ",url:"http://qrator.gsj.intranet/search/keyword?g[]=3&s_v=1",color:"#ffa458",child:[]},
      {name:"プロジェクト",url:"http://qrator.gsj.intranet/search/keyword?g[]=3&p_v=1",color:"#ffa458",child:[]},
      {name:"取引先",url:"http://qrator.gsj.intranet/search/keyword?g[]=3&c_v=1",color:"#ffa458",child:[]},
      {name:"グループ詳細",url:"http://qrator.gsj.intranet/group/detail/3",color:"#ffa458",child:[]}]},
    {name:"営業4グループ",url:"",color:"#ffa458",child:[
      {name:"スタッフ",url:"http://qrator.gsj.intranet/search/keyword?g[]=4&s_v=1",color:"#ffa458",child:[]},
      {name:"プロジェクト",url:"http://qrator.gsj.intranet/search/keyword?g[]=4&p_v=1",color:"#ffa458",child:[]},
      {name:"取引先",url:"http://qrator.gsj.intranet/search/keyword?g[]=4&c_v=1",color:"#ffa458",child:[]},
      {name:"グループ詳細",url:"http://qrator.gsj.intranet/group/detail/4",color:"#ffa458",child:[]}]},
    {name:"エンジニア",url:"",color:"#ffa458",child:[
      {name:"スタッフ",url:"http://qrator.gsj.intranet/search/keyword?g[]=5&s_v=1",color:"#ffa458",child:[]},
      {name:"プロジェクト",url:"http://qrator.gsj.intranet/search/keyword?g[]=5&p_v=1",color:"#ffa458",child:[]},
      {name:"取引先",url:"http://qrator.gsj.intranet/search/keyword?g[]=5&c_v=1",color:"#ffa458",child:[]},
      {name:"グループ詳細",url:"http://qrator.gsj.intranet/group/detail/5",color:"#ffa458",child:[]}]}]},
  {name:"ソリューション事業部",url:"",color:"#ffa458",child:[
    {name:"事業開発",url:"",color:"#ffa458",child:[
      {name:"スタッフ",url:"http://qrator.gsj.intranet/search/keyword?g[]=6&s_v=1",color:"#ffa458",child:[]},
      {name:"プロジェクト",url:"http://qrator.gsj.intranet/search/keyword?g[]=6&p_v=1",color:"#ffa458",child:[]},
      {name:"取引先",url:"http://qrator.gsj.intranet/search/keyword?g[]=6&c_v=1",color:"#ffa458",child:[]},
      {name:"グループ詳細",url:"http://qrator.gsj.intranet/group/detail/6",color:"#ffa458",child:[]}]},
    {name:"製作",url:"",color:"#ffa458",child:[
      {name:"スタッフ",url:"http://qrator.gsj.intranet/search/keyword?g[]=8&s_v=1",color:"#ffa458",child:[]},
      {name:"プロジェクト",url:"http://qrator.gsj.intranet/search/keyword?g[]=8&p_v=1",color:"#ffa458",child:[]},
      {name:"取引先",url:"http://qrator.gsj.intranet/search/keyword?g[]=8&c_v=1",color:"#ffa458",child:[]},
      {name:"グループ詳細",url:"http://qrator.gsj.intranet/group/detail/8",color:"#ffa458",child:[]}]},
    {name:"企画営業",url:"",color:"#ffa458",child:[
      {name:"スタッフ",url:"http://qrator.gsj.intranet/search/keyword?g[]=7&s_v=1",color:"#ffa458",child:[]},
      {name:"プロジェクト",url:"http://qrator.gsj.intranet/search/keyword?g[]=7&p_v=1",color:"#ffa458",child:[]},
      {name:"取引先",url:"http://qrator.gsj.intranet/search/keyword?g[]=7&c_v=1",color:"#ffa458",child:[]},
      {name:"グループ詳細",url:"http://qrator.gsj.intranet/group/detail/7",color:"#ffa458",child:[]}]},
    {name:"TFM",url:"",color:"#ffa458",child:[
      {name:"スタッフ",url:"http://qrator.gsj.intranet/search/keyword?g[]=9&s_v=1",color:"#ffa458",child:[]},
      {name:"プロジェクト",url:"http://qrator.gsj.intranet/search/keyword?g[]=9&p_v=1",color:"#ffa458",child:[]},
      {name:"取引先",url:"http://qrator.gsj.intranet/search/keyword?g[]=9&c_v=1",color:"#ffa458",child:[]},
      {name:"グループ詳細",url:"http://qrator.gsj.intranet/group/detail/9",color:"#ffa458",child:[]}]},
    {name:"マルチメディア",url:"",color:"#ffa458",child:[
      {name:"スタッフ",url:"http://qrator.gsj.intranet/search/keyword?g[]=10&s_v=1",color:"#ffa458",child:[]},
      {name:"プロジェクト",url:"http://qrator.gsj.intranet/search/keyword?g[]=10&p_v=1",color:"#ffa458",child:[]},
      {name:"取引先",url:"http://qrator.gsj.intranet/search/keyword?g[]=10&c_v=1",color:"#ffa458",child:[]},
      {name:"グループ詳細",url:"http://qrator.gsj.intranet/group/detail/10",color:"#ffa458",child:[]}]},
    {name:"開発",url:"",color:"#ffa458",child:[
      {name:"スタッフ",url:"http://qrator.gsj.intranet/search/keyword?g[]=11&s_v=1",color:"#ffa458",child:[]},
      {name:"プロジェクト",url:"http://qrator.gsj.intranet/search/keyword?g[]=11&p_v=1",color:"#ffa458",child:[]},
      {name:"取引先",url:"http://qrator.gsj.intranet/search/keyword?g[]=11&c_v=1",color:"#ffa458",child:[]},
      {name:"グループ詳細",url:"http://qrator.gsj.intranet/group/detail/11",color:"#ffa458",child:[]}]}]},
  {name:"メディアビジネス部",url:"",color:"#ffa458",child:[
    {name:"スタッフ",url:"http://qrator.gsj.intranet/search/keyword?g[]=23&s_v=1",color:"#ffa458",child:[]},
    {name:"プロジェクト",url:"http://qrator.gsj.intranet/search/keyword?g[]=23&p_v=1",color:"#ffa458",child:[]},
    {name:"取引先",url:"http://qrator.gsj.intranet/search/keyword?g[]=23&c_v=1",color:"#ffa458",child:[]},
    {name:"グループ詳細",url:"http://qrator.gsj.intranet/group/detail/23",color:"#ffa458",child:[]}]},
  {name:"イノベーティブビジネス室",url:"",color:"#ffa458",child:[
    {name:"スタッフ",url:"http://qrator.gsj.intranet/search/keyword?g[]=24&s_v=1",color:"#ffa458",child:[]},
    {name:"プロジェクト",url:"http://qrator.gsj.intranet/search/keyword?g[]=24&p_v=1",color:"#ffa458",child:[]},
    {name:"取引先",url:"http://qrator.gsj.intranet/search/keyword?g[]=24&c_v=1",color:"#ffa458",child:[]},
    {name:"グループ詳細",url:"http://qrator.gsj.intranet/group/detail/24",color:"#ffa458",child:[]}]},
  {name:"技術統括室",url:"",color:"#ffa458",child:[
    {name:"スタッフ",url:"http://qrator.gsj.intranet/search/keyword?g[]=15&s_v=1",color:"#ffa458",child:[]},
    {name:"プロジェクト",url:"http://qrator.gsj.intranet/search/keyword?g[]=15&p_v=1",color:"#ffa458",child:[]},
    {name:"取引先",url:"http://qrator.gsj.intranet/search/keyword?g[]=15&c_v=1",color:"#ffa458",child:[]},
    {name:"グループ詳細",url:"http://qrator.gsj.intranet/group/detail/15",color:"#ffa458",child:[]}]},
  {name:"マーケティング＆ＰＲ室",url:"",color:"#ffa458",child:[
    {name:"スタッフ",url:"http://qrator.gsj.intranet/search/keyword?g[]=16&s_v=1",color:"#ffa458",child:[]},
    {name:"プロジェクト",url:"http://qrator.gsj.intranet/search/keyword?g[]=16&p_v=1",color:"#ffa458",child:[]},
    {name:"取引先",url:"http://qrator.gsj.intranet/search/keyword?g[]=16&c_v=1",color:"#ffa458",child:[]},
    {name:"グループ詳細",url:"http://qrator.gsj.intranet/group/detail/16",color:"#ffa458",child:[]}]},
  {name:"経営管理部",url:"",color:"#ffa458",child:[
    {name:"経理財務",url:"",color:"#ffa458",child:[
      {name:"スタッフ",url:"http://qrator.gsj.intranet/search/keyword?g[]=12&s_v=1",color:"#ffa458",child:[]},
      {name:"プロジェクト",url:"http://qrator.gsj.intranet/search/keyword?g[]=12&p_v=1",color:"#ffa458",child:[]},
      {name:"取引先",url:"http://qrator.gsj.intranet/search/keyword?g[]=12&c_v=1",color:"#ffa458",child:[]},
      {name:"グループ詳細",url:"http://qrator.gsj.intranet/group/detail/12",color:"#ffa458",child:[]}]},
    {name:"法務",url:"",color:"#ffa458",child:[
      {name:"スタッフ",url:"http://qrator.gsj.intranet/search/keyword?g[]=13&s_v=1",color:"#ffa458",child:[]},
      {name:"プロジェクト",url:"http://qrator.gsj.intranet/search/keyword?g[]=13&p_v=1",color:"#ffa458",child:[]},
      {name:"取引先",url:"http://qrator.gsj.intranet/search/keyword?g[]=13&c_v=1",color:"#ffa458",child:[]},
      {name:"グループ詳細",url:"http://qrator.gsj.intranet/group/detail/13",color:"#ffa458",child:[]}]},
    {name:"経営企画",url:"",color:"#ffa458",child:[
      {name:"スタッフ",url:"http://qrator.gsj.intranet/search/keyword?g[]=14&s_v=1",color:"#ffa458",child:[]},
      {name:"プロジェクト",url:"http://qrator.gsj.intranet/search/keyword?g[]=14&p_v=1",color:"#ffa458",child:[]},
      {name:"取引先",url:"http://qrator.gsj.intranet/search/keyword?g[]=14&c_v=1",color:"#ffa458",child:[]},
      {name:"グループ詳細",url:"http://qrator.gsj.intranet/group/detail/14",color:"#ffa458",child:[]}]}]},
  {name:"総務部",url:"",color:"#ffa458",child:[
    {name:"総務",url:"",color:"#ffa458",child:[
      {name:"スタッフ",url:"http://qrator.gsj.intranet/search/keyword?g[]=18&s_v=1",color:"#ffa458",child:[]},
      {name:"プロジェクト",url:"http://qrator.gsj.intranet/search/keyword?g[]=18&p_v=1",color:"#ffa458",child:[]},
      {name:"取引先",url:"http://qrator.gsj.intranet/search/keyword?g[]=18&c_v=1",color:"#ffa458",child:[]},
      {name:"グループ詳細",url:"http://qrator.gsj.intranet/group/detail/18",color:"#ffa458",child:[]}]},
    {name:"人事",url:"",color:"#ffa458",child:[
      {name:"スタッフ",url:"http://qrator.gsj.intranet/search/keyword?g[]=17&s_v=1",color:"#ffa458",child:[]},
      {name:"プロジェクト",url:"http://qrator.gsj.intranet/search/keyword?g[]=17&p_v=1",color:"#ffa458",child:[]},
      {name:"取引先",url:"http://qrator.gsj.intranet/search/keyword?g[]=17&c_v=1",color:"#ffa458",child:[]},
      {name:"グループ詳細",url:"http://qrator.gsj.intranet/group/detail/17",color:"#ffa458",child:[]}]}]}]},

{name:"プロジェクト",url:"",color:"#f15f63",child:[
  {name:"モバイル事業部",url:"",color:"#f15f63",child:[
    {name:"営業1グループ",url:"http://qrator.gsj.intranet/search/keyword?g[]=1&p_v=1",color:"#f15f63",child:[]},
    {name:"営業2グループ",url:"http://qrator.gsj.intranet/search/keyword?g[]=2&p_v=1",color:"#f15f63",child:[]},
    {name:"営業3グループ",url:"http://qrator.gsj.intranet/search/keyword?g[]=3&p_v=1",color:"#f15f63",child:[]},
    {name:"営業4グループ",url:"http://qrator.gsj.intranet/search/keyword?g[]=4&p_v=1",color:"#f15f63",child:[]},
    {name:"エンジニア",url:"http://qrator.gsj.intranet/search/keyword?g[]=5&p_v=1",color:"#f15f63",child:[]},
    {name:"すべてをみる",url:"http://qrator.gsj.intranet/search/keyword?d[]=1&p_v=1",color:"#f15f63",child:[]}]},
  {name:"ソリューション事業部",url:"",color:"#f15f63",child:[
    {name:"事業開発",url:"http://qrator.gsj.intranet/search/keyword?g[]=6&p_v=1",color:"#f15f63",child:[]},
    {name:"製作",url:"http://qrator.gsj.intranet/search/keyword?g[]=8&p_v=1",color:"#f15f63",child:[]},
    {name:"企画営業",url:"http://qrator.gsj.intranet/search/keyword?g[]=7&p_v=1",color:"#f15f63",child:[]},
    {name:"マルチメディア",url:"http://qrator.gsj.intranet/search/keyword?g[]=10&p_v=1",color:"#f15f63",child:[]},
    {name:"TFM",url:"http://qrator.gsj.intranet/search/keyword?g[]=9&p_v=1",color:"#f15f63",child:[]},
    {name:"開発",url:"http://qrator.gsj.intranet/search/keyword?g[]=11&p_v=1",color:"#f15f63",child:[]},
    {name:"すべてをみる",url:"http://qrator.gsj.intranet/search/keyword?d[]=2&p_v=1",color:"#f15f63",child:[]}]},
  {name:"メディアビジネス部",url:"http://qrator.gsj.intranet/search/keyword?d[]=49&p_v=1",color:"#f15f63",child:[]},
  {name:"マーケ&PR室",url:"http://qrator.gsj.intranet/search/keyword?d[]=52&p_v=1",color:"#f15f63",child:[]},
  {name:"技術統括室",url:"http://qrator.gsj.intranet/search/keyword?d[]=51&p_v=1",color:"#f15f63",child:[]},
  {name:"イノベーティブビジネス室",url:"http://qrator.gsj.intranet/search/keyword?d[]=50&p_v=1",color:"#f15f63",child:[]},
  {name:"経営管理部",url:"",color:"#f15f63",child:[
    {name:"経理財務",url:"http://qrator.gsj.intranet/search/keyword?g[]=12&p_v=1",color:"#f15f63",child:[]},
    {name:"法務",url:"http://qrator.gsj.intranet/search/keyword?g[]=13&p_v=1",color:"#f15f63",child:[]},
    {name:"経営企画",url:"http://qrator.gsj.intranet/search/keyword?g[]=14&p_v=1",color:"#f15f63",child:[]},
    {name:"すべてをみる",url:"http://qrator.gsj.intranet/search/keyword?d[]=3&p_v=1",color:"#f15f63",child:[]}]},
  {name:"総務部",url:"",color:"#f15f63",child:[
    {name:"総務",url:"http://qrator.gsj.intranet/search/keyword?g[]=18&p_v=1",color:"#f15f63",child:[]},
    {name:"人事",url:"http://qrator.gsj.intranet/search/keyword?g[]=17&p_v=1",color:"#f15f63",child:[]},
    {name:"すべてをみる",url:"http://qrator.gsj.intranet/search/keyword?d[]=4&p_v=1",color:"#f15f63",child:[]}]},
  {name:"キーワード検索",url:"http://qrator.gsj.intranet/search/keyword",color:"#f15f63",child:[]}]},

{name:"スタッフ",url:"",color:"#69c5c2",child:[
  {name:"モバイル事業部",url:"",color:"#69c5c2",child:[
    {name:"営業1グループ",url:"http://qrator.gsj.intranet/search/keyword?g[]=1&s_v=1",color:"#69c5c2",child:[]},
    {name:"営業2グループ",url:"http://qrator.gsj.intranet/search/keyword?g[]=2&s_v=1",color:"#69c5c2",child:[]},
    {name:"営業3グループ",url:"http://qrator.gsj.intranet/search/keyword?g[]=3&s_v=1",color:"#69c5c2",child:[]},
    {name:"営業4グループ",url:"http://qrator.gsj.intranet/search/keyword?g[]=4&s_v=1",color:"#69c5c2",child:[]},
    {name:"エンジニア",url:"http://qrator.gsj.intranet/search/keyword?g[]=5&s_v=1",color:"#69c5c2",child:[]},
    {name:"すべてをみる",url:"http://qrator.gsj.intranet/search/keyword?d[]=1&s_v=1",color:"#69c5c2",child:[]}]},
  {name:"ソリューション事業部",url:"",color:"#69c5c2",child:[
    {name:"事業開発",url:"http://qrator.gsj.intranet/search/keyword?g[]=6&s_v=1",color:"#69c5c2",child:[]},
    {name:"製作",url:"http://qrator.gsj.intranet/search/keyword?g[]=8&s_v=1",color:"#69c5c2",child:[]},
    {name:"企画営業",url:"http://qrator.gsj.intranet/search/keyword?g[]=7&s_v=1",color:"#69c5c2",child:[]},
    {name:"マルチメディア",url:"http://qrator.gsj.intranet/search/keyword?g[]=10&s_v=1",color:"#69c5c2",child:[]},
    {name:"TFM",url:"http://qrator.gsj.intranet/search/keyword?g[]=9&s_v=1",color:"#69c5c2",child:[]},
    {name:"開発",url:"http://qrator.gsj.intranet/search/keyword?g[]=11&s_v=1",color:"#69c5c2",child:[]},
    {name:"すべてをみる",url:"http://qrator.gsj.intranet/search/keyword?d[]=2&s_v=1",color:"#69c5c2",child:[]}]},
  {name:"メディアビジネス部",url:"http://qrator.gsj.intranet/search/keyword?g[]=23&s_v=1",color:"#69c5c2",child:[]},
  {name:"マーケ&PR室",url:"http://qrator.gsj.intranet/search/keyword?g[]=16&s_v=1",color:"#69c5c2",child:[]},
  {name:"技術統括室",url:"http://qrator.gsj.intranet/search/keyword?g[]=15&s_v=1",color:"#69c5c2",child:[]},
  {name:"イノベーティブビジネス室",url:"http://qrator.gsj.intranet/search/keyword?g[]=24&s_v=1",color:"#69c5c2",child:[]},
  {name:"経営管理部",url:"",color:"#69c5c2",child:[
    {name:"経理財務",url:"http://qrator.gsj.intranet/search/keyword?g[]=12&s_v=1",color:"#69c5c2",child:[]},
    {name:"法務",url:"http://qrator.gsj.intranet/search/keyword?g[]=13&s_v=1",color:"#69c5c2",child:[]},
    {name:"経営企画",url:"http://qrator.gsj.intranet/search/keyword?g[]=14&s_v=1",color:"#69c5c2",child:[]},
    {name:"すべてをみる",url:"http://qrator.gsj.intranet/search/keyword?d[]=3&s_v=1",color:"#69c5c2",child:[]}]},
  {name:"総務部",url:"",color:"#69c5c2",child:[
    {name:"総務",url:"http://qrator.gsj.intranet/search/keyword?g[]=18&s_v=1",color:"#69c5c2",child:[]},
    {name:"人事",url:"http://qrator.gsj.intranet/search/keyword?g[]=17&s_v=1",color:"#69c5c2",child:[]},
    {name:"すべてをみる",url:"http://qrator.gsj.intranet/search/keyword?d[]=4&s_v=1",color:"#69c5c2",child:[]}]}]},

{name:"取引先",url:"",color:"#4ab386",child:[
  {name:"モバイル事業部",url:"",color:"#4ab386",child:[
    {name:"営業1グループ",url:"http://qrator.gsj.intranet/search/keyword?g[]=1&c_v=1",color:"#4ab386",child:[]},
    {name:"営業2グループ",url:"http://qrator.gsj.intranet/search/keyword?g[]=2&c_v=1",color:"#4ab386",child:[]},
    {name:"営業3グループ",url:"http://qrator.gsj.intranet/search/keyword?g[]=3&c_v=1",color:"#4ab386",child:[]},
    {name:"営業4グループ",url:"http://qrator.gsj.intranet/search/keyword?g[]=4&c_v=1",color:"#4ab386",child:[]},
    {name:"エンジニア",url:"http://qrator.gsj.intranet/search/keyword?g[]=5&c_v=1",color:"#4ab386",child:[]},
    {name:"すべてをみる",url:"http://qrator.gsj.intranet/search/keyword?d[]=1&c_v=1",color:"#4ab386",child:[]}]},
  {name:"ソリューション事業部",url:"",color:"#4ab386",child:[
    {name:"事業開発",url:"http://qrator.gsj.intranet/search/keyword?g[]=6&c_v=1",color:"#4ab386",child:[]},
    {name:"製作",url:"http://qrator.gsj.intranet/search/keyword?g[]=8&c_v=1",color:"#4ab386",child:[]},
    {name:"企画営業",url:"http://qrator.gsj.intranet/search/keyword?g[]=7&c_v=1",color:"#4ab386",child:[]},
    {name:"マルチメディア",url:"http://qrator.gsj.intranet/search/keyword?g[]=10&c_v=1",color:"#4ab386",child:[]},
    {name:"TFM",url:"http://qrator.gsj.intranet/search/keyword?g[]=9&c_v=1",color:"#4ab386",child:[]},
    {name:"開発",url:"http://qrator.gsj.intranet/search/keyword?g[]=11&c_v=1",color:"#4ab386",child:[]},
    {name:"すべてをみる",url:"http://qrator.gsj.intranet/search/keyword?d[]=2&c_v=1",color:"#4ab386",child:[]}]},
  {name:"メディアビジネス部",url:"http://qrator.gsj.intranet/search/keyword?g[]=23&c_v=1",color:"#4ab386",child:[]},
  {name:"マーケ&PR室",url:"http://qrator.gsj.intranet/search/keyword?g[]=16&c_v=1",color:"#4ab386",child:[]},
  {name:"技術統括室",url:"http://qrator.gsj.intranet/search/keyword?g[]=15&c_v=1",color:"#4ab386",child:[]},
  {name:"イノベーティブビジネス室",url:"http://qrator.gsj.intranet/search/keyword?g[]=24&c_v=1",color:"#4ab386",child:[]},
  {name:"経営管理部",url:"",color:"#4ab386",child:[
    {name:"経理財務",url:"http://qrator.gsj.intranet/search/keyword?g[]=12&c_v=1",color:"#4ab386",child:[]},
    {name:"法務",url:"http://qrator.gsj.intranet/search/keyword?g[]=13&c_v=1",color:"#4ab386",child:[]},
    {name:"経営企画",url:"http://qrator.gsj.intranet/search/keyword?g[]=14&c_v=1",color:"#4ab386",child:[]},
    {name:"すべてをみる",url:"http://qrator.gsj.intranet/search/keyword?d[]=3&c_v=1",color:"#4ab386",child:[]}]},
  {name:"総務部",url:"",color:"#4ab386",child:[
    {name:"総務",url:"http://qrator.gsj.intranet/search/keyword?g[]=18&c_v=1",color:"#4ab386",child:[]},
    {name:"人事",url:"http://qrator.gsj.intranet/search/keyword?g[]=17&c_v=1",color:"#4ab386",child:[]},
    {name:"すべてをみる",url:"http://qrator.gsj.intranet/search/keyword?d[]=4&c_v=1",color:"#4ab386",child:[]}]}]},

{name:"キーワード検索",url:"http://qrator.gsj.intranet/search/keyword",color:"#c3c3c3",child:[]}

]